services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: totalfutbol
      POSTGRES_PASSWORD: totalfutbol
      POSTGRES_DB: totalfutbol
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
